apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vd1mq6mkb-dotnet-basic
  janus-idp.io/tekton: vd1mq6mkb-dotnet-basic
  backstage.io/kubernetes-id: vd1mq6mkb-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vd1mq6mkb-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
